
- name : Mon playbook
  hosts: all
  become: true 
  tasks:
    - name : webservers-group caracteristique
      debug:
        msg: "{{server_type}}"  "{{cloud_provider}}"  "{{ec2_type}}"
      
        
      

