
- name : Mon playbook
  hosts: all
  become: yes 
  tasks:
    - name: check connection
      ping: 

    - name: get group_vars (webservers)
      debug:
        msg: "Groupe de de serveur : {{server_group_name}} | Fournisseur cloud : {{cloud_provider}}"  

    - name: get host_vars (ubuntu@172.31.39.90)
      debug:
        msg: "type de serveur : {{server_type}}"  

    - name: create user mugen
      user: 
        name: mugen
        state: present 
        groups: sudo
        password: "{{ 'malyoun123' | password_hash('sha512') }}"
      register : user_mugen

    - name: debug user mugen
      debug:
        var: user_mugen

    - name: create a file for the user
      file:
        path: "/home/mugen/mugen.txt"
        state: touch
        owner: mugen
        group: root
        mode: 0755      

