
- name : Mon playbook
  hosts: all
  become: true 
  tasks:
    - name : webservers-group caracteristique
      debug:
        msg: "{{server_type}}"
      debug:
        msg: "{{cloud_provider}}"
      debug:
        msg: "{{ec2_type}}"
        
      

