
- name : Mon playbook
  hosts: all
  become: true 
  tasks:
    - name : webservers-group caracteristique
      debug:
        msg: "type de serveur : {{server_type}} | Fournisseur cloud : {{cloud_provider}} | Type d'instance: {{ec2_type}}"  
      
        
      

