
- name : Mon playbook
  host: all
  become: true 
  tasks:
    - name : webservers-group caracteristique
      debug:
        msg: {{"server_type"}}
        msg: {{"cloud_provider"}}
        msg: {{"ec2_type"}}
